social_auth_github.settings:
  type: config_object
  label: 'Social Auth Github settings'
  mapping:
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'App Secret'
    graph_version:
      type: float
      label: 'Github Graph API version'
